#!/usr/bin/env python3
"""Render references/runbook.md from references/runbook.template.md + facts/environment.json.

The facts file is the single source for environment facts (plan KTD7): the runbook's
gotcha section is generated from it, and classify-failure.py matches traces against the
same patterns. Usage:
  render-runbook.py [--root <plugin root>] [--check]
--check exits 1 when the checked-in runbook differs from a fresh render (CI diff gate).
Stdlib only, Python 3.9.
"""
import argparse, json, os, sys

MARK_BEGIN = "<!-- facts:begin (generated by ops/render-runbook.py — edit facts/environment.json, not this block) -->"
MARK_END = "<!-- facts:end -->"


def render_facts(facts):
    out = [MARK_BEGIN, "", "| Fact | Class | Retry safe | Bites at | Recorded in |", "|---|---|---|---|---|"]
    for f in facts:
        out.append("| `%s` | %s | %s | %s | `%s` |" % (
            f["id"], f["class"], "yes" if f.get("retry_safe") else "no", f["step"], f["source"]))
    out.append("")
    for f in facts:
        out.append("### `%s`" % f["id"])
        out.append("")
        out.append(f["explanation"].strip())
        out.append("")
        out.append("Signature: `%s`" % f["pattern"])
        out.append("")
    out.append(MARK_END)
    return "\n".join(out)


def render(root):
    facts = json.load(open(os.path.join(root, "facts", "environment.json")))["facts"]
    tpl = open(os.path.join(root, "references", "runbook.template.md")).read()
    if "{{FACTS}}" not in tpl:
        sys.exit("template lacks {{FACTS}} placeholder")
    return tpl.replace("{{FACTS}}", render_facts(facts))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    out_path = os.path.join(a.root, "references", "runbook.md")
    rendered = render(a.root)
    if a.check:
        current = open(out_path).read() if os.path.exists(out_path) else ""
        if current != rendered:
            print(json.dumps({"ok": False, "error": "runbook_stale",
                              "message": "references/runbook.md differs from a fresh render; run ops/render-runbook.py"}))
            sys.exit(1)
        print(json.dumps({"ok": True, "checked": out_path}))
        return
    with open(out_path, "w") as fh:
        fh.write(rendered)
    print(json.dumps({"ok": True, "rendered": out_path, "facts": rendered.count("\n### `")}))


if __name__ == "__main__":
    main()
